#!/bin/bash

# MIT License
#
# Copyright (c) 2017 Jonathan Barda
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Small script that let you connect and sync to your host without having
# the ssh port always open by using the port knocking technique.
# Just setup the connection sequence on your server then define it in this script.

# Requires the `onchange.sh` script to be installed on your system
# Also required, inotifiy-tools

# Config
USER=
PASS=
HOST=
SEQ=""
LIMITER=/proc/sys/fs/inotify/max_user_watches
WATCHES=16384
IN=""
OUT=""

# Sets the limit
sudo su -c "echo ${WATCHES} > ${LIMITER}"

# Moving to the directory to sync
pushd $IN

# Starts the sync
onchange.sh "knock -v ${HOST} ${SEQ} && rsync -pvtxhse 'sshpass -p ${PASS} ssh -l ${USER}' --recursive --force --compress --itemize-changes --stats --progress --delete-after --exclude=index.html --exclude=report*.html ${IN} ${HOST}:${OUT} && notify-send 'Sync sucess !' || notify-send 'Sync failure...'"
